### ISSUE TITLE
类似于header 不能设置单独一行么

### ISSUE THREAD

**Issue by DirZhang** [hs-web/reactor-excel#1]
我从代码中并没有找到相应的设置

**Comment by zhou-hao** [comment]
没明白啥意思

**Comment by DirZhang** [comment]
excel 第一行要 整个一行都显示一个字段，像这样
![image](https://user-images.githubusercontent.com/42533530/96220244-f2657080-0fba-11eb-84a7-611a6c053d0b.png)

**Comment by zhou-hao** [comment]
目前没有提供类似API。有兴趣的话可以提提pr。 应该修改WriterOperator类的write方法，让HeaderCell类的rowIndex可以设置

**Comment by DirZhang** [comment]
好

**Comment by DirZhang** [comment]
大哥能加微信么

**Comment by DirZhang** [comment]
我的微信 18646129972

**Comment by zhou-hao** [comment]
现在可以看看
```java
 ReactorExcel
                .xlsxWriter()
```
相关API
