### ISSUE TITLE
PoiCell#isCellDateFormatted获取数字类型异常

### ISSUE THREAD

**Issue by AntsMa** [hs-web/reactor-excel#11]
调用org.hswebframework.reactor.excel.Cell#getType获取类型时，调用方法org.hswebframework.reactor.excel.poi.PoiCell#isCellDateFormatted，isCellDateFormatted方法中cell.getNumericCellValue()方法没有判断是否是数字类型，直接获取数字类型的值导致类型转换异常

**Comment by AntsMa** [comment]
只要调用org.hswebframework.reactor.excel.Cell#getType方法，读取到的不是数字类型字符串，这里是100%复现，走到这个default方法就会报错
![image](https://github.com/user-attachments/assets/28a08be1-67db-493a-a8a6-6455ae8152db)

**Comment by zhou-hao** [comment]
使用最新代码试试
