### ISSUE TITLE
怎么获取当前Sheet的名称或者索引

### ISSUE THREAD

**Issue by AntsMa** [hs-web/reactor-excel#8]
需求背景说明：通过第一个sheet解析数据，获取其中的值，然后通过该值动态的读取其它Sheet的数据，每个Sheet内容不同，标题不同，并且组合在一起。
无论从justRead，还是multiSheet都无法实现。justRead无法知道Sheet的名称索引，multiSheet只能指定读取指定已知Sheet的值。
目前看没有办法实现上述需求

**Comment by zhou-hao** [comment]
自定义 wrapper. 和 instanceCondition 试试 ?  将 Cell转为 InSheetCell 来获取sheet名称和索引。

**Comment by AntsMa** [comment]
> 自定义 wrapper. 和 instanceCondition 试试 ? 将 Cell转为 InSheetCell 来获取sheet名称和索引。

cell强转为BoundedCell实现获取，BoundedCell boundedCell = ((BoundedCell) cell)
